config/routes.rb
Rails.application.routes.draw do
  #get 'pages/home'
  
  
  #root to: "home#index"
  devise_for :users
  
  
  resources :books do
    
    resources :reviews
  end
  root "books#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :category
    belongs_to :user
    has_many :reviews
    
    
    validates :title, presence: true, length: {maximum: 30}
    validates :description, presence: true
    
    validates :author, presence: true, length: {maximum: 30}
    
    
  has_attached_file :book_img, styles: { :book_index => "250x350>", :book_show => "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
end

app/models/review.rb
class Review < ApplicationRecord
    
    belongs_to :book
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    if @book.reviews.blank?
      @average_raview = 0
    else
      @average_raview = @book.reviews.average(:rating).round(2)
      
    end
  end

  # GET /books/new
  def new
    @book = current_user.books.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  # GET /books/1/edit
  def edit
    #@book = Book.find(params[:id])
   @categories = Category.all.map{ |c| [c.name, c.id] } 
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.build(book_params)
    @book.category_id = params[:category_id]

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    @book.category_id = params[:category_id]
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :description, :author, :book_img, :category_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    
    before_action :find_book
    before_action :find_review, only: [:edit, :update, :destroy]
    
    def new
       @review = Review.new
    end
    
    def create
     @review = Review.new(review_params)
     @review.book_id = @book.id
     @review.user_id = current_user.id
        
     if @review.save
         redirect_to book_path(@book)
     else
        render 'new'
     end
    end
    
    def edit
       
    end
    
    def update
        if @review.update(review_params)
            redirect_to book_path(@book)
        else
            render 'edit'
        end
        
    end
    
    def destroy
        @review.destroy
        redirect_to book_path(@book)
        
    end
    
    private
    
    def review_params
        params.require(:review).permit(:rating, :comment)
        
    end
    
    def find_book
        @book = Book.find(params[:book_id])
    end
    
    def find_review
        @review = Review.find(params[:id])
        
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

<%= form_for @book, url: books_path, html: { multipart: true } do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
    
      <!-- %= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %> -->


      <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select catgory") %>
      
      <%= form.label :タイトル %>
      <%= form.text_field :title %>
      
      
      <%= form.label :表紙 %>
      <%= form.file_field :book_img %>

      <%= form.label :本の内容 %>
      <%= form.text_area :description %>

      <%= form.label :著者 %>
      <%= form.text_field :author %>

      <%= form.submit "作成", class: "btn btn-primary" %>

  

<% end %>

  
  
  

</div>
</div>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> 
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<div class="center jumbotron main_body">

<h2>書籍一覧</h2>


<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
      <th>著者</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= book.author %></td>
        <td><%= image_tag book.book_img.url(:book_index) %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <!-- <td>%= link_to 'Destroy',books_url, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
  
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

</div>

app/views/books/new.html.erb
<h1>新しく本を作成</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<!-- 
<p>
  <strong>タイトル:</strong>
  <%= @book.title %>
</p>
 
 %= image_tag url_for(@book.image) %>
%= link_to @book.image.filename, rails_blob_path(@book.image, disposition: "attachment") %>

<p>
  <strong>内容:</strong>
  %= @book.description %>
</p>

<p>
  <strong>カテゴリー:</strong>
  %= @book.category.name %>
</p>

<p>
  <strong>著者:</strong>
  %= @book.author %>
</p> -->



<div class="row">
    <div class="col-md-4">
        <%= image_tag @book.book_img.url(:book_show),class: "book-show"%>
    </div>
    
    <div class="col-md-8">
        <h2><%= @book.title%></h2>
        <h3><%= @book.author %></h3>
        <h2>平均レビュー</h2>
        <div class="average-review-rating" data-score= <%= @average_review %>></div>
        <p><%= @book.description %></p>
    </div>
</div>


<div class="row">
    <div class="col-md-4">
        <%= render @book.reviews %>
       <div>
          <%= link_to "レビューの追加", new_book_review_path(@book) %>
       </div>
</div>
</div>


<%= link_to 'Back', books_path %>
<% if user_signed_in? %>

<% if @book.user_id == current_user.id %>
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Delete', book_path(@book), method: :delete, data: {confirm: "are you sure??"} %>


<% end %>

<% end %>


<script>
    $('.review-rating').raty({
        readOnly: true,
        score: function() {
            return $(this).attr('data-score');
        },
        path: '/assets/'
    });
</script>

app/views/layouts/_alert.html.erb
 <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       
       

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        
        <nav>
         <ul class="nav navbar-nav navbar-right">
             <% if current_user%>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
             
             <% else%>
               <li><%= link_to "Log in", new_user_session_path %></li>
               <li><%= link_to "Sign Up", new_user_registration_path %></li>
             
             <% end %>
             
            
         </ul>
        </nav>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookレビュー</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
      <%= render 'layouts/header' %>
      
     <div class="container">
        
        <%= 'layouts/alert' %>
        <%= yield %>
        <%= render 'layouts/footer' %>
     </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/_form.html.erb
<%= form_for([@book, @book.reviews.build]) do |f| %>
<div id ="rating-form">
  <label>レーティング</label>
  </div>
  <%= f.input :comment %>
  <%= f.input :submit %>
<% end%>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<div class="review-rating" data-score="<%= review.rating %>"></div>
<p><%= review.comment %></p>


<% if user_signed_in? %>
  <% if review.user_id == current_user.id %>

<%= link_to "Edit", edit_book_review_path(review.book, review)%>
<%= link_to "Delete", book_review_path(review.book, review), method: :delete, data: {confirm: "本当によろしいですか？？"} %>

<% end %>
<% end %>

app/views/reviews/edit.html.erb
<h1>レビューの編集</h1>

<%= form_for([@book, @reviews]) do |f| %>
  <%= f.input :rating%>
  <%= f.input :comment %>
  <%= f.input :submit %>
<% end%>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/new.html.erb
<h1>新規レビュー作成</h1>

<%= render 'form' %>